import React, { useState, useEffect, useRef } from "react";
import styles from "./AUT.module.css"; // Importing the CSS module
import { useNavigate, useLocation } from "react-router-dom";
import Instructions from "../Instructions/Instructions";
import { useSurvey } from "../../surveyIDContext";
import * as XLSX from "xlsx";

function AUT() {
  const [useCases, setUseCases] = useState(() =>
    Array.from({ length: 15 }, () => ({ use: "", explanation: "" }))
  );
  const { surveyId, setSurveyId } = useSurvey();

  const navigate = useNavigate();
  // const location = useLocation();
  // const { preSurveyId } = location.state || {}; // Ensure a fallback if state is undefined

  const preSurveyId = surveyId;
  // console.log("preSurveyId", preSurveyId);

  const [data, setData] = useState([]); // State to store the entire dataset
  const [randomString, setRandomString] = useState("");

  useEffect(() => {
    async function fetchAndParseXLSX() {
      // const response = await fetch("/src/assets/AUT_Database.xlsx");
      // const arrayBuffer = await response.arrayBuffer();

      // // Reading the file
      // const workbook = XLSX.read(arrayBuffer, { type: "buffer" });

      // // Convert first worksheet to JSON (assuming the first sheet is what you want)
      // const firstSheet = workbook.Sheets[workbook.SheetNames[0]];
      // const jsonData = XLSX.utils.sheet_to_json(firstSheet, { header: 1 });

      // // Save the entire dataset
      // setData(jsonData);
      // console.log("DATA: ", jsonData);
      let L = [
        "Object",
        "3D Printer Filament",
        "Accordion Folder",
        "Acupressure Mat",
        "Address Plaque",
        "Adjustable Dumbbell",
        "Adjustable Wrench",
        "Aerobic Step Platform",
        "Agility Ladder",
        "AirPods Case",
        "Airplane Ticket",
        "Alarm Clock",
        "Ankle Brace",
        "Ankle Weights",
        "Apple",
        "Arm Compression Sleeve",
        "Back Scratcher",
        "Backpack",
        "Backpacking Pack",
        "Badge Clip",
        "Badge Holder",
        "Badminton Birdie",
        "Balloon",
        "Ballpoint Pen",
        "Banana Peel",
        "Bandaid",
        "Bar Stool",
        "Barbecue Skewers",
        "Baseball Bat",
        "Basket",
        "Basketball Hoop",
        "Bath Towel",
        "Bathrobe",
        "Battery",
        "Battery Tester",
        "Beach Towel",
        "Beach Volleyball",
        "Bear Spray",
        "Beard Grooming Kit",
        "Bed Pillow",
        "Bee House",
        "Belt",
        "Bicycle Bell",
        "Bicycle Tire",
        "Bike Helmet",
        "Bike Lock",
        "Bike Pump",
        "Bike Repair Kit",
        "Bike Speedometer",
        "Billiard Cue Stick",
        "Binoculars",
        "Bird Feeder",
        "Blender",
        "Blue Light Blocking Glasses",
        "Bobby Pin",
        "Bocce Ball Set",
        "Body Scrubber",
        "Body Toning Belt",
        "Book",
        "Book Stand",
        "Bookend",
        "Bottle",
        "Bottle Brush",
        "Bottle Cap",
        "Bottle Opener",
        "Bottle Stopper",
        "Bowling Ball Bag",
        "Brick",
        "Broom",
        "Broom Handle",
        "Broomstick",
        "Bubble Wrap",
        "Bug Spray",
        "Bulletin Board",
        "Bungee Cord",
        "Bungee Cords",
        "Butterfly Net",
        "Button",
        "CD Case",
        "CD/DVD",
        "Cable Clips",
        "Cable Management Box",
        "Cable Organizer",
        "Cable Tester",
        "Cable Tie",
        "Calculator",
        "Calendar",
        "Camera Lens Cap",
        "Camera Strap",
        "Camping Chair",
        "Camping Hammock",
        "Camping Mess Kit",
        "Camping Stove",
        "Can Strainer",
        "Candle",
        "Candle Holder",
        "Candle Jar",
        "Candy Wrapper",
        "Car Floor Mat",
        "Car Jump Starter",
        "Car Key",
        "Car Phone Holder",
        "Car Seat Cover",
        "Car Steering Wheel Cover",
        "Carabiner Clip",
        "Carabiner Lock",
        "Carabiner Mug",
        "Cardboard Box",
        "Cardboard Tube",
        "Carpet Remnant",
        "Carpet Sample",
        "Cereal Box",
        "Chair",
        "Chapstick",
        "Cheese Cloth",
        "Cheese Grater",
        "Chewing Gum Wrapper",
        "Chip Clip",
        "Chopsticks",
        "Cinnamon Stick",
        "Circuit Board",
        "Cleaning Sponge",
        "Climbing Chalk Bag",
        "Climbing Harness",
        "Climbing Rope",
        "Clipboard",
        "Clipboard Hook",
        "Clothes Hanger",
        "Clothespin",
        "Coaster",
        "Coat Hanger",
        "Coat Rack",
        "Coffee Can",
        "Coffee Cup Lid",
        "Coffee Filter",
        "Coffee Mug",
        "Coin",
        "Colander",
        "Collapsible Cooler",
        "Compact Mirror",
        "Compass",
        "Compost Bin",
        "Compression Sack",
        "Compression Socks",
        "Contact Lens Case",
        "Cooling Pad",
        "Cork",
        "Cork Board",
        "Cork Coaster",
        "Corkboard",
        "Cornhole Board",
        "Cotton Ball",
        "Cotton Swabs",
        "Couch Cushion",
        "Crockpot",
        "Crutches",
        "Curtain Ring",
        "Curtain Rod",
        "Curtain Tiebacks",
        "Cutting Board",
        "Cycling Shoe Clips",
        "Dartboard Cabinet",
        "Dash Cam",
        "Deck of Cards",
        "Decorative Pillow",
        "Decorative Vase",
        "Desk Fan",
        "Desk Lamp",
        "Desk Organizer",
        "Dice",
        "Digital Clock",
        "Digital Scoreboard",
        "Dinner Plate",
        "Disc Golf Basket",
        "Disposable Cup",
        "Document Sleeve",
        "Dog Leash",
        "Dollhouse Furniture",
        "Door Hinge",
        "Door Knob",
        "Doorknob",
        "Doormat",
        "Doorstop",
        "Drafting Compass",
        "Drawer Liner",
        "Drill Bit",
        "Drinking Glass",
        "Drinking Straw",
        "Drone Propeller",
        "Drumstick",
        "Duct Tape",
        "Duct Tape Roll",
        "Dumbbells",
        "Dustpan",
        "Easel",
        "Egg Beater",
        "Egg Carton",
        "Egg Holder",
        "Egg Separator",
        "Egg Timer",
        "Elastic Band",
        "Electric Fan",
        "Electric Kettle",
        "Electric Nail File",
        "Electric Skateboard Remote",
        "Emergency Road Flare",
        "Emergency Thermal Blanket",
        "Emergency Whistle",
        "Envelope",
        "Eraser",
        "Ergonomic Seat Cushion",
        "Ethernet Cable",
        "Exercise Ball",
        "Extension Cord",
        "External Hard Drive",
        "Eyeglass Case",
        "Eyeglasses Case",
        "Fabric Belt",
        "Fabric Scraps",
        "Face Mask",
        "Face Steamer",
        "Facial Roller",
        "Fanny Pack",
        "Feather Duster",
        "Fertilizer Spreader",
        "Figure Skating Guards",
        "File Folder",
        "Filing Cabinet",
        "Fire Extinguisher",
        "Fire Starter Flint",
        "Fireplace Tools",
        "First Aid Kit",
        "Fishing Hook",
        "Fishing Line",
        "Fishing Net",
        "Fishing Rod",
        "Fishing Tackle Box",
        "Flash Drive",
        "Flashlight",
        "Flower Pot",
        "Fly Swatter",
        "Foam Mat",
        "Foam Pad",
        "Foam Roller",
        "Foam Roller Stick",
        "Foam Yoga Block",
        "Foldable Scooter",
        "Folding Chair",
        "Folding Shovel",
        "Food Processor",
        "Foot Spa Basin",
        "Football",
        "Footrest",
        "Fork",
        "Frisbee",
        "Funnel",
        "Garden Fence",
        "Garden Gnome",
        "Garden Hose",
        "Garden Lantern",
        "Garden Spade",
        "Garden Windmill",
        "Garlic Press",
        "Gas Can",
        "Gift Bag",
        "Gift Box",
        "Gift Wrap Tube",
        "Gimbal Stabilizer",
        "Glass Bottle",
        "Glass Jar",
        "Globe",
        "Glove",
        "Glove Box Organizer",
        "Gloves",
        "Glue Stick",
        "GoPro Mount",
        "Goggles",
        "Golf Club",
        "Golf Tee",
        "Grocery Bag",
        "Guitar String",
        "Gym Towel Clip",
        "HDMI Splitter",
        "Hair Band",
        "Hair Brush",
        "Hair Clip",
        "Hair Straightener Brush",
        "Hammock",
        "Hand Fan",
        "Hand Gripper",
        "Hand Mirror",
        "Hand Sanitizer Bottle",
        "Handheld Massager",
        "Handkerchief",
        "Hanger",
        "Harmonica",
        "Hat",
        "Headband",
        "Headlamp",
        "Headphones",
        "Hearing Aid",
        "Hearing Protection Earmuffs",
        "Heat Shrink Tubing",
        "Hedge Clippers",
        "Helmet",
        "Helmet Visor",
        "Herb Scissors",
        "Hex Key Set",
        "Highlighter",
        "Hiking Gaiters",
        "Hockey Puck",
        "Hockey Stick",
        "Honey Dipper",
        "Hose Clamp",
        "Hose Reel",
        "Hot Water Bottle",
        "Hydration Pack",
        "Hydration Vest",
        "Ice Cream Scoop",
        "Ice Cube Tray",
        "Ice Pack",
        "Ice Scraper",
        "Index Card",
        "Index Cards",
        "Inline Skate Wheels",
        "Insulated Water Jug",
        "Ironing Board",
        "Jar Lid",
        "Jigsaw Puzzle",
        "Juice Carton",
        "Jump Rope",
        "Jumper Cables",
        "Kayak Paddle",
        "Kettlebell Handle",
        "Key",
        "Key Lanyard",
        "Keyboard Wrist Rest",
        "Keychain",
        "Kite",
        "Kite Frame",
        "Kite String",
        "Knee Brace",
        "Knee Support Wrap",
        "Lacrosse Stick",
        "Ladder",
        "Lampshade",
        "Lantern",
        "Laptop Bag",
        "Laptop Case",
        "Laptop Cooling Pad",
        "Laptop Stand",
        "Laser Pointer",
        "Laundry Basket",
        "Lawn Chair",
        "Lawn Edger",
        "Leaf Blower",
        "Legal Pad",
        "Lemon",
        "Lemon Zester",
        "Letter Opener",
        "Light Bulb",
        "Lip Balm",
        "Lollipop Stick",
        "Luggage",
        "Luggage Tag",
        "Lunch Box",
        "Magazine",
        "Magazine Holder",
        "Magnet",
        "Magnetic Chess Set",
        "Magnetic Phone Mount",
        "Magnetic Strip",
        "Magnetic Therapy Bracelet",
        "Mailbox",
        "Makeup Brush",
        "Makeup Sponge",
        "Matchbox",
        "Matchstick",
        "Measuring Cup",
        "Measuring Spoon",
        "Measuring Tape",
        "Measuring Wheel",
        "Meat Thermometer",
        "Mechanical Keyboard",
        "Memory Card",
        "Metal Can",
        "Metal Spoon",
        "Metal Wire",
        "Microphone",
        "Microwave",
        "Microwave Plate",
        "Milk Jug",
        "Mini Basketball Hoop",
        "Mirror",
        "Mixing Bowl",
        "Monitor Riser",
        "Mortar and Pestle",
        "Motorcycle Gloves",
        "Mouse Pad",
        "Mug",
        "Multimeter",
        "Multitool",
        "Nail Clippers",
        "Nail File",
        "Napkin",
        "Napkin Holder",
        "Neck Traction Pillow",
        "Neck Warmer",
        "Necklace",
        "Network Switch",
        "Newspaper",
        "Noise-Canceling Earplugs",
        "Notebook",
        "Notepad",
        "Oil Dispenser",
        "Old CD",
        "Old Credit Card",
        "Old Newspaper",
        "Oscilloscope",
        "Outdoor Clock",
        "Oven Mitt",
        "Oven Rack",
        "PVC Pipe",
        "Packing Peanuts",
        "Packing Tape",
        "Paint Can",
        "Paintbrush",
        "Paper Cup",
        "Paper Towel Roll",
        "Paperclip",
        "Paperweight",
        "Parachute Cord",
        "Paracord Bracelet",
        "Paring Knife",
        "Passport Cover",
        "Peanut Butter Jar",
        "Pedometer",
        "Pen Cap",
        "Pencil",
        "Pencil Sharpener",
        "Pepper Grinder",
        "Perfume Bottle",
        "Phone Case",
        "Phone Charger",
        "Phone Ring Holder",
        "Pickleball Paddle",
        "Picture Frame",
        "Pilates Ring",
        "Pillowcase",
        "Ping Pong Ball",
        "Ping Pong Net",
        "Ping Pong Paddle",
        "Pizza Box",
        "Pizza Cutter",
        "Planter Box",
        "Plastic Bag",
        "Plastic Clip",
        "Plastic Container",
        "Plastic Cup",
        "Plastic Egg",
        "Plastic Fork",
        "Plastic Funnel",
        "Plastic Pipe",
        "Plastic Spool",
        "Plastic Spoon",
        "Plastic Straw",
        "Plastic Tongs",
        "Plastic Toy",
        "Plastic Wrap",
        "Plunger",
        "Pocket Blanket",
        "Pocket Flashlight",
        "Pocket Knife",
        "Pool Noodle",
        "Popsicle Stick",
        "Portable Air Compressor",
        "Portable Breathalyzer",
        "Portable Charger",
        "Portable Espresso Maker",
        "Portable Fan",
        "Portable Fan Mist Sprayer",
        "Portable Fire Pit",
        "Portable Folding Stool",
        "Portable SSD",
        "Portable Toothbrush Sanitizer",
        "Portable Water Filter",
        "Postcard",
        "Poster Tube",
        "Posture Corrector",
        "Pot Holder",
        "Pot Lid",
        "Potting Soil Bag",
        "Power Drill Bit Set",
        "Printer Paper",
        "Projector",
        "Projector Screen",
        "Punching Bag",
        "Push Pin",
        "Puzzle Box",
        "Puzzle Piece",
        "Racing Helmet",
        "Rain Barrel",
        "Rain Gauge",
        "Raincoat",
        "Ratchet Strap",
        "Recipe Book",
        "Reflective Safety Vest",
        "Refrigerator Magnet",
        "Resistance Bands",
        "Resistance Loop Bands",
        "Reusable Ice Pack",
        "Rice Cooker",
        "Rolling Cart",
        "Rolling Pin",
        "Rolling Suitcase",
        "Roof Rack",
        "Rope",
        "Rope Swing",
        "Router Stand",
        "Rowing Oar",
        "Rubber Band",
        "Rubber Duck",
        "Rubber Eraser",
        "Rubber Glove",
        "Ruler",
        "Safety Pin",
        "Safety Scissors",
        "Salad Spinner",
        "Salt Shaker",
        "Sandal",
        "Scarf",
        "School Bag",
        "Scissors",
        "Screw",
        "Screw Organizer",
        "Screwdriver",
        "Scrunchie",
        "Selfie Stick",
        "Sewing Kit",
        "Shampoo Bottle",
        "Shoe Box",
        "Shoe Inserts",
        "Shoe Laces",
        "Shoelace",
        "Shopping Bag",
        "Shower Cap",
        "Shower Squeegee",
        "Silicone Baking Mat",
        "Skateboard",
        "Ski Goggles",
        "Ski Pole",
        "Sleeping Bag",
        "Smart Scale",
        "Smartwatch Dock",
        "Snake Bite Kit",
        "Snow Shovel",
        "Snowboard Leash",
        "Snowshoe Poles",
        "Soap Bar",
        "Soap Dish",
        "Soccer Ball",
        "Soccer Goal Net",
        "Sock",
        "Soda Bottle",
        "Soda Can",
        "Soil Sifter",
        "Solar Charger",
        "Solar Path Lights",
        "Solar-Powered Lantern",
        "Soldering Iron",
        "Spatula",
        "Speed Jump Rope",
        "Spice Rack",
        "Sponge",
        "Spoon",
        "Spray Bottle",
        "Sprinkler",
        "Stadium Seat Cushion",
        "Stainless Steel Straw",
        "Staple Remover",
        "Stapler",
        "Step Ladder",
        "Stepladder",
        "Sticky Tack",
        "Stirring Stick",
        "Stopwatch",
        "Storage Bin",
        "String Lights",
        "Suction Cup Hook",
        "Sun Visor Clip",
        "Sunglasses",
        "Sunscreen Bottle",
        "Surfboard",
        "Surge Protector",
        "Survival Knife",
        "Swiss Army Knife",
        "TV Remote",
        "Tabletop Air Hockey",
        "Tackle Box",
        "Tea Infuser",
        "Tea Kettle",
        "Telescoping Walking Stick",
        "Tennis Ball",
        "Tennis Ball Basket",
        "Tennis Racket",
        "Tent Pegs",
        "Thermal Blanket",
        "Thermometer",
        "Thermos",
        "Tin Can",
        "Tin Foil",
        "Tire Inflator",
        "Tire Patch Kit",
        "Tissue Box",
        "Toaster",
        "Toilet Paper Roll",
        "Tool Roll",
        "Toolbox",
        "Toothbrush",
        "Toothpaste Tube",
        "Toothpick",
        "Towel",
        "Towel Rack",
        "Trampoline Springs",
        "Travel Mug",
        "Travel Pillow",
        "Treadmill Lubricant",
        "Trekking Backpack",
        "Trekking Pole",
        "Tripod",
        "Tripod Mount",
        "Trunk Organizer",
        "Tumbler",
        "Tupperware Lid",
        "Tweezers",
        "USB Cable",
        "USB Hub",
        "UV Sterilizer Wand",
        "Umbrella",
        "Umbrella Stand",
        "Underwater Flashlight",
        "Utility Belt",
        "VR Headset",
        "Vacuum Hose",
        "Vase",
        "Velcro Strap",
        "Velcro Strip",
        "Velcro Tape",
        "Waffle Maker",
        "Walkie-Talkie",
        "Walking Cane",
        "Wall Hook",
        "Water Bottle",
        "Water Polo Cap",
        "Waterproof Matches",
        "Waterproof Notebook",
        "Weather Vane",
        "Weed Barrier",
        "Weightlifting Belt",
        "Weightlifting Chalk",
        "Weightlifting Gloves",
        "Wet Wipes",
        "Wheel",
        "Wheelbarrow",
        "Wheelchair",
        "Whisk",
        "Whistle",
        "Whiteboard",
        "Wind Chime",
        "Window Blind",
        "Windshield De-icer",
        "Windshield Sunshade",
        "Wire Basket",
        "Wire Strippers",
        "Wireless Earbuds",
        "Wireless Mouse",
        "Wooden Block",
        "Wooden Hanger",
        "Wooden Ruler",
        "Wrench",
        "Wrist Wraps",
        "Wristwatch",
        "Yoga Block",
        "Yoga Bolster",
        "Yoga Mat",
        "Yoga Strap",
        "Ziploc Bag",
        "Zipper",
      ];
      await setData(L);
      // Selecting a random string from the first column of a random row
      console.log("Outside IF");
      if (data.length > 0) {
        console.log("DATA inside IF: ", data);
        const randomIndex = Math.floor(Math.random() * data.length);
        setRandomString(data[randomIndex]);
        const data = [
          ...data.slice(0, randomIndex),
          ...data.slice(randomIndex + 1),
        ];
        // Update local state (optional, if you want to see the array post removal in ComponentA)
        // setData(newArray);
      }
    }

    fetchAndParseXLSX();
  }, []);

  const hasRunOnce = useRef(false);

  useEffect(() => {
    if (data.length > 0 && !hasRunOnce.current) {
      console.log("DATA inside IF: ");
      const randomIndex = Math.floor(Math.random() * data.length);
      setRandomString(data[randomIndex]);

      const newData = [
        ...data.slice(0, randomIndex),
        ...data.slice(randomIndex + 1),
      ];

      setData(newData);
      hasRunOnce.current = true; // Mark as run once
    }
  }, [data]);

  const handleChange = (index, type, value) => {
    const newUseCases = [...useCases];
    newUseCases[index][type] = value;
    setUseCases(newUseCases);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log(
      "Sending data:",
      JSON.stringify({ useCases, preSurveyId: preSurveyId })
    );

    // Simple client-side validation
    // if (useCases.some((uc) => !uc.use.trim() || !uc.explanation.trim())) {
    //   alert("All fields must be filled out.");
    //   return;
    // }

    try {
      // console.log("PreSurveyId", preSurveyId);
      let NODE_api = import.meta.env.VITE_NODE_API + "/AUT";
      const response = await fetch(NODE_api, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          useCases,
          preSurveyId: preSurveyId,
          object: randomString,
        }),
      });
      if (response.ok) {
        navigate("/Task2Page", { state: { data: data } });
      } else {
        alert("Failed to submit form");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("Failed to submit form due to an error.");
    }
  };

  return (
    <>
      <Instructions />
      <div className={styles.container}>
        <h1>TASK 1</h1>
        <p>
          List as many alternative uses as possible for the following objects
          and provide a reasonable explanation for each use:
        </p>
        <br></br>
        <div className={styles.header}>
          {/* <img
            src="../../assets/bicycle-pump.png"
            alt="Bicycle Pump"
            className={styles.image}
          /> */}
          <h2 className={styles.title}>{randomString}</h2>
        </div>
        <form onSubmit={handleSubmit}>
          {useCases.map((item, index) => (
            <div key={index} className={styles.useCaseGroup}>
              <input
                type="text"
                placeholder={`Use Case #${index + 1}`}
                value={item.use}
                onChange={(e) => handleChange(index, "use", e.target.value)}
                className={styles.inputField}
              />
              <input
                type="text"
                placeholder="Explanation"
                value={item.explanation}
                onChange={(e) =>
                  handleChange(index, "explanation", e.target.value)
                }
                className={styles.inputField}
              />
            </div>
          ))}
          <button type="submit" className={styles.submitButton}>
            Submit
          </button>
        </form>
      </div>
    </>
  );
}

export default AUT;
